language: java
sudo: false
script: ant build
before_script: cd CaulCrafting
before_install:
  - wget http://dariusmtn.fr/caulcrafting/spigotjar/Spigot-1.12.jar
  - wget http://dariusmtn.fr/caulcrafting/spigotjar/Spigot-1.11.2.jar
  - wget http://dariusmtn.fr/caulcrafting/spigotjar/Spigot-1.10.jar
  - wget http://dariusmtn.fr/caulcrafting/spigotjar/Spigot-1.9_R1.jar
  - wget http://dariusmtn.fr/caulcrafting/spigotjar/Spigot-1.9_R2.jar
notifications:
  email: false
deploy:
  provider: releases
  api-key: ${GITHUB_TOKEN}
  file:
  - target/CaulCrafting.jar
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
 
